/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pelajar;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
/**
 *
 * @author HP
 */
public class Siswi extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    ResultSet Rssiswi=null;
    /**
     * Creates new form Siswi
     */
    public Siswi() {
        initComponents();
         Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height > screenSize.height){
        frameSize.height=screenSize.height;
        }
        if(frameSize.width > screenSize.width){
        frameSize.width=screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height = screenSize.height) / 20); 
        
        tampilData();
        SetEditOff();
    }
    
    private void tampilData(){
        try{
            Object[] judul_kolom = {"NIS", "Nama", "Kelas", "Jurusan"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            TabelSiswi.setModel(tabModel);
            
            Connection conn=(Connection)Koneksi.KoneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            Rssiswi=stt.executeQuery("SELECT * from siswi ");  
            while(Rssiswi.next()){
                Object[] data={
                    Rssiswi.getString("NIS"),
                    Rssiswi.getString("Nama"),
                    Rssiswi.getString("Kelas"),
                    Rssiswi.getString("Jurusan"),        
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
        // disable button
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonCancel.setEnabled(false);
    }
        
         //menampilkan data ke form saat data pada tabel di klik 
   void tblKeForm(){
        jTextNIS.setText(tabModel.getValueAt(TabelSiswi.getSelectedRow(),0)+"");
        jTextNama.setText(tabModel.getValueAt(TabelSiswi.getSelectedRow(),1)+"");
        jTextKelas.setText(tabModel.getValueAt(TabelSiswi.getSelectedRow(),2)+"");
        jComboBoxJurusan.setSelectedItem(tabModel.getValueAt(TabelSiswi.getSelectedRow(),3)+"");
        
        
        jButtonUpdate.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonSave.setEnabled(false);
    }
   
     
   //membersihkan form
   private void BersihData(){
        jTextNIS.setText("");
        jTextNama.setText("");
        jTextKelas.setText(""); 
        jComboBoxJurusan.setSelectedIndex(0);
       
    } 
   
   //disable form
   private void SetEditOff(){
        jTextNIS.setEnabled(false);
        jTextNama.setEnabled(false);
        jTextKelas.setEnabled(false);
        jComboBoxJurusan.setEnabled(false);

   }
   
   
   private void seteditOn(){
        jTextNIS.setEnabled(true);
        jTextNama.setEnabled(true);
        jTextKelas.setEnabled(true);
        jComboBoxJurusan.setEnabled(true);
       
   }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                      
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNIS = new javax.swing.JTextField();
        jLabelHeader = new javax.swing.JLabel();
        jLabelNIS = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jTextNama = new javax.swing.JTextField();
        jLabelKelas = new javax.swing.JLabel();
        jTextKelas = new javax.swing.JTextField();
        jLabelJurusan = new javax.swing.JLabel();
        jComboBoxJurusan = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelSiswi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelHeader.setText("Data Siswi");

        jLabelNIS.setText("NIS");

        jLabelNama.setText("Nama");

        jLabelKelas.setText("Kelas");

        jTextKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKelasActionPerformed(evt);
            }
        });

        jLabelJurusan.setText("Jurusan");

        jComboBoxJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RPL", "TKJ", "AP", "FARMASI", "TELIN", "TSM", "TKRO", " " }));

        jButtonAdd.setText("AddNew");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        TabelSiswi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Kelas", "Jurusan"
            }
        ));
        TabelSiswi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelSiswiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelSiswi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButtonSave)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDelete))
                            .addComponent(jTextKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancel))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdd)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextNIS)
                                .addComponent(jTextNama)
                                .addComponent(jComboBoxJurusan, 0, 207, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabelHeader)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAdd)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonSave))
                .addGap(32, 85, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextKelas)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(203, 203, 203))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
           BersihData();
        jTextNIS.requestFocus();
        jButtonSave.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        seteditOn();
                 
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        String NIS=jTextNIS.getText();
        String Nama=jTextNama.getText();
        String Kelas=jTextKelas.getText();
        String Jurusan=jComboBoxJurusan.getSelectedItem().toString();

        if (NIS.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"NIS tidak boleh kosong");
            jTextNIS.requestFocus();
        }else if (Nama.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama tidak boleh kosong");
            jTextNama.requestFocus();
        }else if (Kelas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kelas tidak boleh kosong");
            jTextKelas.requestFocus();
        }else if (Jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jurusan tidak boleh kosong");
            jComboBoxJurusan.requestFocus();
       
        }
        else if (!(new Scanner(Kelas).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Kelas harus angka");
            jTextKelas.requestFocus();
        
        }else{
            try{
                Connection conn=(Connection)Koneksi.KoneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("insert into Siswi(NIS,Nama,Kelas,Jurusan)"+"VALUES('"+NIS+"','"+Nama+"','"+Kelas+"','"+Jurusan+"')");
                BersihData();
                tampilData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String NIS=jTextNIS.getText();
        String Nama=jTextNama.getText();
        String Kelas=jTextKelas.getText();
        String Jurusan=jComboBoxJurusan.getSelectedItem().toString();

        if (NIS.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"NIS tidak boleh kosong");
            jTextNIS.requestFocus();
        }else if (Nama.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Nama tidak boleh kosong");
            jTextNama.requestFocus();
        }else if (Kelas.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Kelas tidak boleh kosong");
            jTextKelas.requestFocus();
        }else if (Jurusan.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Jurusan tidak boleh kosong");
            jComboBoxJurusan.requestFocus();
       
        }
        else if (!(new Scanner(Kelas).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Kelas harus angka");
            jTextKelas.requestFocus();
      
        }else{
            try{
                Connection conn=(Connection)Koneksi.KoneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("UPDATE Siswi SET Nama='"+Nama+"', Kelas='"+Kelas+"', "+"Jurusan='"+Jurusan+"' WHERE NIS='"+NIS+"'");
                BersihData();
                tampilData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil diubah","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Ubah data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
           String NIS=jTextNIS.getText();

        if (NIS.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"NIS tidak boleh kosong");
            jTextNIS.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection conn=(Connection)Koneksi.KoneksiDB();
            Statement stt=conn.createStatement();
            stt.executeUpdate("DELETE FROM Siswi WHERE NIS='"+NIS+"'");
            BersihData();
            tampilData();
            SetEditOff();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        BersihData();
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        SetEditOff();  
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void TabelSiswiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelSiswiMouseClicked
        // TODO add your handling code here:
         seteditOn();
        jTextNIS.setEnabled(false);
        tblKeForm();
    }//GEN-LAST:event_TabelSiswiMouseClicked

    private void jTextKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelSiswi;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxJurusan;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelJurusan;
    private javax.swing.JLabel jLabelKelas;
    private javax.swing.JLabel jLabelNIS;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextKelas;
    private javax.swing.JTextField jTextNIS;
    private javax.swing.JTextField jTextNama;
    // End of variables declaration//GEN-END:variables

    
}
